# Generated by Django 5.2.1 on 2025-06-19 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaissePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salar', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_bordereau', models.BooleanField(default=False)),
                ('is_devise', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_stock', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_stock', to='gestion.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='BordereauCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereau_in_caisse', to='gestion.caissepos')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('respo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('reste', models.FloatField()),
                ('date_recouvrement', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributeur_achat', to='gestion.distributeur')),
                ('posCible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cible', to='gestion.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='ListPayAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_on_achat', to='gestion.achat')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat_money_echange', to='gestion.caissepos')),
            ],
        ),
        migrations.AddField(
            model_name='caissepos',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_caisse', to='gestion.pointvente'),
        ),
        migrations.CreateModel(
            name='ApprovisionnementPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('reste', models.FloatField()),
                ('date_recouvrement', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('posCible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_recepteur', to='gestion.pointvente')),
                ('posDistributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_distributeur', to='gestion.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributeur_product', to='gestion.distributeur')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantity_max', models.IntegerField()),
                ('prixAchat', models.FloatField()),
                ('prixVente', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_pos', to='gestion.pointvente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_product_pos', to='gestion.products')),
            ],
        ),
        migrations.CreateModel(
            name='ListProductApprovionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prixAchat', models.FloatField()),
                ('prixVente', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_pos_product', to='gestion.approvisionnementpos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_appro_for', to='gestion.products')),
            ],
        ),
        migrations.CreateModel(
            name='ListProductAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prixAchat', models.FloatField()),
                ('prixVente', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_achat_info', to='gestion.achat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_distr_for', to='gestion.products')),
            ],
        ),
        migrations.CreateModel(
            name='BasketListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePerUnitOfficiel', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisproduct_for_basket', to='gestion.basketagent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_for_agent', to='gestion.products')),
            ],
        ),
        migrations.CreateModel(
            name='RecouvrementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('respo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respo_recouvrement', to=settings.AUTH_USER_MODEL)),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_money_echange', to='gestion.typeechange')),
            ],
        ),
        migrations.CreateModel(
            name='RendreProduitPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_received', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_render', to=settings.AUTH_USER_MODEL)),
                ('panier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier_rendu', to='gestion.basketagent')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_receiver', to='gestion.pointvente')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_render', to=settings.AUTH_USER_MODEL)),
                ('recouvrement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_rendu', to='gestion.recouvrementvente')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitRenduPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePerUnitOfficiel', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_rendu', to='gestion.products')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_product_pos', to='gestion.rendreproduitpos')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsablePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son_POS', to='gestion.pointvente')),
                ('respo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respo_POS', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaireUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son_poste', to='gestion.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_respo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('is_salaire', models.BooleanField(default=False)),
                ('is_tool', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_depense', to='gestion.caissepos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respo_depense', to=settings.AUTH_USER_MODEL)),
                ('user_depense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_depense', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_depense', to='gestion.toolsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TauxEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.FloatField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devise_type', to='gestion.typeechange')),
            ],
        ),
        migrations.CreateModel(
            name='ListPayApprovisionnementPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_on_approv', to='gestion.approvisionnementpos')),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approv_money_echange', to='gestion.typeechange')),
            ],
        ),
        migrations.AddField(
            model_name='caissepos',
            name='typeEchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_echange_caisse', to='gestion.typeechange'),
        ),
        migrations.CreateModel(
            name='TypeEchangeRenduPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_typeEchange_pos', to='gestion.rendreproduitpos')),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeEchange_rendu', to='gestion.typeechange')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reste', models.FloatField()),
                ('date_recouvrement', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vente', to='gestion.customer')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_vente', to='gestion.basketagent')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEchangeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_money_echange', to='gestion.typeechange')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_on_vente', to='gestion.vente')),
            ],
        ),
        migrations.AddField(
            model_name='rendreproduitpos',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vente_rendu', to='gestion.vente'),
        ),
        migrations.AddField(
            model_name='recouvrementvente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_vente', to='gestion.vente'),
        ),
        migrations.CreateModel(
            name='ListProductVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePerUnitOfficiel', models.FloatField()),
                ('pricePerUnitClient', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vente', to='gestion.products')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_vente', to='gestion.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTypeBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_user', to='gestion.basketagent')),
            ],
        ),
    ]
