# Generated by Django 5.2.1 on 2025-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_is_agent_commercial_user_is_respo_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
