# Generated by Django 5.2.1 on 2025-06-24 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_agent', to=settings.AUTH_USER_MODEL)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_pos', to='gestion.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prixVente', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_product', to='gestion.products')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='gestion.requestagent')),
            ],
        ),
    ]
