# Generated by Django 5.2.1 on 2025-06-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productapprovisionnement',
            name='approvisionnement',
        ),
        migrations.RemoveField(
            model_name='productapprovisionnement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productapprovisionnement',
            name='stock',
        ),
        migrations.CreateModel(
            name='ListProductAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prixAchat', models.FloatField()),
                ('prixVente', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_achat_info', to='gestion.achat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_distr_for', to='gestion.products')),
            ],
        ),
        migrations.CreateModel(
            name='ListProductApprovionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_pos_product', to='gestion.approvisionnementpos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_appro_for', to='gestion.products')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_appro_from', to='gestion.productpointvente')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAchat',
        ),
        migrations.DeleteModel(
            name='ProductApprovisionnement',
        ),
    ]
