# Generated by Django 5.2.1 on 2025-05-24 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_delivered', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_transaction', to=settings.AUTH_USER_MODEL)),
                ('walletCible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_cible', to='gestion.wallet')),
                ('walletSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_source', to='gestion.wallet')),
            ],
        ),
    ]
