# Generated by Django 5.2.1 on 2025-06-05 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_listpayachat_listpayapprovisionnementpos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendreProduitPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_received', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_render', to=settings.AUTH_USER_MODEL)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_receiver', to='gestion.pointvente')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_render', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitRenduPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePerUnitOfficiel', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_rendu', to='gestion.products')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_product_pos', to='gestion.rendreproduitpos')),
            ],
        ),
    ]
