# Generated by Django 5.2.1 on 2025-06-02 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_pointvente_respo_poste_date_responsablepos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='distributeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distributeur_product', to='gestion.distributeur'),
            preserve_default=False,
        ),
    ]
