# Generated by Django 5.2.1 on 2025-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_products_distributeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
