# Generated by Django 5.2.1 on 2025-05-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_wallettypebasket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletUserPos',
        ),
    ]
