# Generated by Django 5.2.1 on 2025-06-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rendreproduitpos_produitrendupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEchangeRenduPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_typeEchange_pos', to='gestion.rendreproduitpos')),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeEchange_rendu', to='gestion.typeechange')),
            ],
        ),
    ]
