# Generated by Django 5.2.1 on 2025-05-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_walletuserpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reste', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vente', to='gestion.customer')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_vente', to='gestion.basketagent')),
            ],
        ),
    ]
