# Generated by Django 5.2.1 on 2025-06-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('prixAchat', models.FloatField()),
                ('prixVente', models.FloatField()),
                ('date_expiration', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_pos', to='gestion.pointvente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_product_pos', to='gestion.products')),
            ],
        ),
    ]
