# Generated by Django 5.2.1 on 2025-06-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_typeechangerendupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaissePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_caisse', to='gestion.pointvente')),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_echange_caisse', to='gestion.typeechange')),
            ],
        ),
        migrations.CreateModel(
            name='BordereauCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereau_in_caisse', to='gestion.caissepos')),
            ],
        ),
    ]
