# Generated by Django 5.2.1 on 2025-06-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_caissepos_bordereaucaisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecouvrementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('bordereau', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_money_echange', to='gestion.typeechange')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_vente', to='gestion.vente')),
            ],
        ),
    ]
