# Generated by Django 5.2.1 on 2025-05-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProductVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePerUnitOfficiel', models.FloatField()),
                ('pricePerUnitClient', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vente', to='gestion.products')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_vente', to='gestion.vente')),
            ],
        ),
    ]
