# Generated by Django 5.2.1 on 2025-06-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_productpointvente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('reste', models.FloatField()),
                ('date_recouvrement', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributeur_achat', to='gestion.distributeur')),
                ('posCible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cible', to='gestion.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovisionnementPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('reste', models.FloatField()),
                ('date_recouvrement', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('posCible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_recepteur', to='gestion.pointvente')),
                ('posDistributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_distributeur', to='gestion.pointvente')),
            ],
        ),
    ]
