# Generated by Django 5.2.1 on 2025-05-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_listproductvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettypebasket',
            name='berdereau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TypeEchangeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('typeEchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_money_echange', to='gestion.typeechange')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_on_vente', to='gestion.vente')),
            ],
        ),
    ]
