# Generated by Django 5.2.1 on 2025-05-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_wallettypebasket_berdereau_typeechangevente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettypebasket',
            old_name='berdereau',
            new_name='bordereau',
        ),
        migrations.AddField(
            model_name='typeechangevente',
            name='bordereau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='typeechangevente',
            name='montant',
            field=models.FloatField(),
        ),
    ]
