# Generated by Django 5.2.1 on 2025-06-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_recouvrementvente_respo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendreproduitpos',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier_rendu', to='gestion.basketagent'),
        ),
        migrations.AddField(
            model_name='rendreproduitpos',
            name='recouvrement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrement_rendu', to='gestion.recouvrementvente'),
        ),
        migrations.AddField(
            model_name='rendreproduitpos',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vente_rendu', to='gestion.vente'),
        ),
    ]
