# Generated by Django 5.2.1 on 2025-05-29 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_berdereau_wallettypebasket_bordereau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_recouvrement',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
