# Generated by Django 5.2.1 on 2025-06-10 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_toolsuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_depense', to='gestion.caissepos')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_depense', to='gestion.toolsuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respo_depense', to=settings.AUTH_USER_MODEL)),
                ('user_depense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_depense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
