# Generated by Django 5.2.1 on 2025-06-10 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_depenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
