# Generated by Django 5.2.1 on 2025-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_depenses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenses',
            name='is_salaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depenses',
            name='is_tool',
            field=models.BooleanField(default=False),
        ),
    ]
