# Generated by Django 5.2.1 on 2025-06-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_depenses_is_salaire_depenses_is_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpayachat',
            name='typeEchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat_money_echange', to='gestion.caissepos'),
        ),
    ]
