# Generated by Django 5.2.1 on 2025-06-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_listpayachat_typeechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listpayachat',
            old_name='typeEchange',
            new_name='caisse',
        ),
    ]
